import Head from "next/head";

export const AuthLayout = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <div className="row">
          <div className="col-md-6 offset-md-3">
            <h2 className="text-center text-dark mt-5">{ title }</h2>
            <div className="text-center mb-5 text-dark fs-5">Next Template</div>
            {children}
          </div>
        </div>
      </main>
    </>
  );
};
